### PR TITLE
doc: add package.conf example, closes HYB-555

### PR DESCRIPTION
**Pull request by Obero**

### CODE REVIEW

**Comment by Obero** [comment]
Draft until feature release

**Comment by Obero** [comment]
Please discuss common subjects about `package.conf` example here: https://github.com/gatling/gatling-sbt-plugin-demo/pull/31

**Comment by Isammoc** [comment]
Removed myself as reviewer from this one, because only comments will be done in [sbt's PR](https://github.com/gatling/gatling-sbt-plugin-demo/pull/31)

**Review by tpetillot — APPROVED** [review]

**Comment by Obero** [comment]
Removed myself as reviewer from this one, because only comments will be done in https://github.com/gatling/gatling-sbt-plugin-demo/pull/31

It's ready, I bring you back :D

**Review by Isammoc — APPROVED** [review]

**Pull request merged**
